
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./Footer/page";
import Header from "./Header/page";
import Subscribe from "./Subscribe/page";
import SocialMedia from "./SocialMedia/page";
import Aos from '../Component/Aos.js/page'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <Header/>
       <main>
        <Aos/>
        {children}
       </main>
       <Subscribe/>
        <SocialMedia/>
        <Footer/>
      </body>
    </html>
  );
}
